#!/bin/bash

FWDIR="$(cd `dirname $0`; pwd)"

export PROJECT_HOME="$FWDIR"

unset JAVA_HOME

export R_PROFILE_USER="/tmp/sparkR.profile"

if [ $# -gt 0 ]; then
  # If we are running an R program, only set libPaths and use Rscript
cat > /tmp/sparkR.profile << EOF
.First <- function() {
  projecHome <- Sys.getenv("PROJECT_HOME")
  classPath <- Sys.getenv("CLASSPATH")
  javaHome <- Sys.getenv("JAVA_HOME")
  scalaHome <- Sys.getenv("SCALA_HOME")
  .libPaths( c(paste(projecHome,"/lib", sep=""), 
	       paste(scalaHome,"/lib", sep=""),
           .libPaths()))
  cat("Setting SparkR profile PROJECT_HOME ", projecHome, "/n")
  cat("Setting SparkR profile JAVA_HOME is set as: ", javaHome, "/n")
  cat("Setting SparkR profile SCALA_HOME is set as :", scalaHome, "/n")
  cat("Setting SparkR profile library paths: ",.libPaths())
  Sys.setenv(NOAWT=1)
}
EOF

  Rscript "$@"
else

  # If we don't have an R file to run, initialize context and run R
cat > /tmp/sparkR.profile << EOF
.First <- function() {
  projecHome <- Sys.getenv("PROJECT_HOME")
  classPath <- Sys.getenv("CLASSPATH")
  javaHome <- Sys.getenv("JAVA_HOME")
  scalaHome <- Sys.getenv("SCALA_HOME")
  Sys.setenv(NOAWT=1)
  .libPaths(c(paste(projecHome,"/lib", sep=""),
	      paste(scalaHome,"/lib", sep=""),
	    .libPaths()))
  require(rJava)
  require(SparkR)
  sc <- sparkR.init(Sys.getenv("MASTER", unset = "local"))
  assign("sc", sc, envir=.GlobalEnv)
  cat("Setting SparkR profile PROJECT_HOME ", projecHome, "/n")
  cat("Setting SparkR profile JAVA_HOME is set as: ", javaHome, "/n")
  cat("Setting SparkR profile SCALA_HOME is set as :", scalaHome, "/n")
  cat("Setting SparkR profile library paths: ", .libPaths(), "/n")
  cat("\n Welcome to SparkR!")
  cat("\n Spark context is available as sc\n")
}
EOF

  R
fi
